import type { Book, SiteConfig } from "@/lib/types";

export const siteConfig: SiteConfig = {
  name: "Sarthak Pani",
  description:
    "Essays and reading notes from Sarthak Pani on engineering, AI, physics, products, and building.",
  url: "https://sarthakpani.com",
  email: "official.sarthakp@gmail.com",
  socials: {
    github: "https://github.com/kingsarthucodes",
    linkedin: "https://www.linkedin.com/in/sarthak-pani-b675a22a8/",
  },
};

export const books: Book[] = [
  {
    title: "Astrophysics for People in a Hurry",
    author: "Neil deGrasse Tyson",
    status: "read",
    cover: "/books/covers/7984709.webp",
    sourceUrl: "https://openlibrary.org/works/OL17710047W",
  },
  {
    title: "Post Office",
    author: "Charles Bukowski",
    status: "read",
    cover: "/books/covers/670128.webp",
    sourceUrl: "https://openlibrary.org/works/OL50457W",
  },
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    status: "read",
    cover: "/books/covers/7884018.webp",
    sourceUrl: "https://openlibrary.org/works/OL276558W",
  },
  {
    title: "The Odyssey",
    author: "Homer",
    status: "read",
    cover: "/books/covers/12474938.webp",
    sourceUrl: "https://openlibrary.org/works/OL26446888W",
  },
  {
    title: "Kafka on the Shore",
    author: "Haruki Murakami",
    status: "read",
    cover: "/books/covers/13234513.webp",
    sourceUrl: "https://openlibrary.org/works/OL2625431W",
  },
  {
    title: "A Confederacy of Dunces",
    author: "John Kennedy Toole",
    status: "read",
    cover: "/books/covers/10397126.webp",
    sourceUrl: "https://openlibrary.org/works/OL3501723W",
  },
  {
    title: "What I Talk About When I Talk About Running",
    author: "Haruki Murakami",
    status: "read",
    cover: "/books/covers/13185830.webp",
    sourceUrl: "https://openlibrary.org/works/OL31446613W",
  },
  {
    title: "The Capitalist Manifesto",
    author: "Johan Norberg",
    status: "read",
    cover: "/books/sarthak-reading-stack.webp",
    coverPosition: "50% 28%",
    coverScale: 3.2,
    sourceUrl: "https://openlibrary.org/works/OL730074W",
  },
  {
    title: "The Farewell Waltz",
    author: "Milan Kundera",
    status: "read",
    cover: "/books/covers/42951.webp",
    sourceUrl: "https://openlibrary.org/works/OL13054848W",
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    status: "read",
    cover: "/books/covers/14860515.webp",
    sourceUrl: "https://openlibrary.org/works/OL1268413W",
  },
  {
    title: "Hard-Boiled Wonderland and the End of the World",
    author: "Haruki Murakami",
    status: "read",
    cover: "/books/covers/14558822.webp",
    sourceUrl: "https://openlibrary.org/works/OL25435388W",
  },
  {
    title: "Birthday Stories",
    author: "Haruki Murakami, editor",
    status: "read",
    cover: "/books/covers/892313.webp",
    sourceUrl: "https://openlibrary.org/works/OL2625408W",
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    status: "read",
    cover: "/books/covers/8634250.webp",
    sourceUrl: "https://openlibrary.org/works/OL17075811W",
  },
  {
    title: "1984",
    author: "George Orwell",
    status: "read",
    cover: "/books/covers/14351142.webp",
    sourceUrl: "https://openlibrary.org/works/OL30827457W",
  },
  {
    title: "Outliers",
    author: "Malcolm Gladwell",
    status: "read",
    cover: "/books/covers/10021591.webp",
    sourceUrl: "https://openlibrary.org/works/OL5749847W",
  },
  {
    title: "Player Piano",
    author: "Kurt Vonnegut",
    status: "read",
    cover: "/books/covers/280246.webp",
    sourceUrl: "https://openlibrary.org/works/OL98484W",
  },
  {
    title: "Riotous Assembly",
    author: "Tom Sharpe",
    status: "read",
    cover: "/books/covers/660414.webp",
    sourceUrl: "https://openlibrary.org/works/OL14937818W",
  },
  {
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    status: "read",
    cover: "/books/covers/12727001.webp",
    sourceUrl: "https://openlibrary.org/works/OL98459W",
  },
  {
    title: "The Bhagavad Gita",
    author: "Eknath Easwaran, translator",
    status: "read",
    cover: "/books/covers/4213511.webp",
    sourceUrl: "https://openlibrary.org/works/OL15892503W",
  },
  {
    title: "Naked Economics",
    author: "Charles Wheelan",
    status: "read",
    cover: "/books/covers/247593.webp",
    sourceUrl: "https://openlibrary.org/works/OL8061775W",
  },
  {
    title: "The Tin Drum",
    author: "Günter Grass",
    status: "read",
    cover: "/books/covers/10325868.webp",
    sourceUrl: "https://openlibrary.org/works/OL67334W",
  },
  {
    title: "Catch-22",
    author: "Joseph Heller",
    status: "read",
    cover: "/books/covers/6468653.webp",
    sourceUrl: "https://openlibrary.org/works/OL276798W",
  },
  {
    title: "Land of the Seven Rivers",
    author: "Sanjeev Sanyal",
    status: "read",
    cover: "/books/covers/7333915.webp",
    sourceUrl: "https://openlibrary.org/works/OL17077865W",
  },
  {
    title: "Animal Farm",
    author: "George Orwell",
    status: "read",
    cover: "/books/covers/11261770.webp",
    sourceUrl: "https://openlibrary.org/works/OL1168007W",
  },
  {
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    status: "read",
    cover: "/books/covers/7279515.webp",
    sourceUrl: "https://openlibrary.org/works/OL16818208W",
  },
  {
    title: "The Far Pavilions",
    author: "M. M. Kaye",
    status: "read",
    cover: "/books/covers/174038.webp",
    sourceUrl: "https://openlibrary.org/works/OL1985695W",
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    status: "read",
    cover: "/books/covers/12621906.webp",
    sourceUrl: "https://openlibrary.org/works/OL267171W",
  },
  {
    title: "The Ride of a Lifetime",
    author: "Robert Iger",
    status: "read",
    cover: "/books/covers/8788773.webp",
    sourceUrl: "https://openlibrary.org/works/OL20140592W",
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    status: "read",
    cover: "/books/covers/12374726.webp",
    sourceUrl: "https://openlibrary.org/works/OL16085155W",
  },
  {
    title: "Basic Writings of Existentialism",
    author: "Gordon Marino, editor",
    status: "read",
    cover: "/books/covers/8037485.webp",
    sourceUrl: "https://openlibrary.org/works/OL17756079W",
  },
  {
    title: "Invent and Wander",
    author: "Jeff Bezos",
    status: "read",
    cover: "/books/covers/10229085.webp",
    sourceUrl: "https://openlibrary.org/works/OL20895272W",
  },
];
